# Generated by Django 5.0.2 on 2024-03-24 10:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ph_number', models.CharField(max_length=15)),
                ('skills', models.CharField(max_length=100)),
                ('working_from', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Vardas')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Tel. nr.:')),
                ('make', models.CharField(max_length=100, verbose_name='Markė:')),
                ('model', models.CharField(max_length=100, verbose_name='Modelis:')),
                ('number_plate', models.CharField(max_length=10, verbose_name='Tr. pr. nr.:')),
                ('vin_number', models.CharField(max_length=17, verbose_name='Vin numeris:')),
                ('year', models.IntegerField(verbose_name='Pagaminimo metai:')),
                ('engine_type', models.CharField(max_length=10, verbose_name='Variklio tipas:')),
                ('driven_axle', models.CharField(max_length=10, verbose_name='Varančioji ašis:')),
                ('body_type', models.CharField(max_length=12, verbose_name='Kėbulo tipas:')),
                ('gearbox_type', models.CharField(max_length=10, verbose_name='Pavarų dėžė:')),
                ('engine_power_kw', models.IntegerField(choices=[(40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125), (126, 126), (127, 127), (128, 128), (129, 129), (130, 130), (131, 131), (132, 132), (133, 133), (134, 134), (135, 135), (136, 136), (137, 137), (138, 138), (139, 139), (140, 140), (141, 141), (142, 142), (143, 143), (144, 144), (145, 145), (146, 146), (147, 147), (148, 148), (149, 149), (150, 150), (151, 151), (152, 152), (153, 153), (154, 154), (155, 155), (156, 156), (157, 157), (158, 158), (159, 159), (160, 160), (161, 161), (162, 162), (163, 163), (164, 164), (165, 165), (166, 166), (167, 167), (168, 168), (169, 169), (170, 170), (171, 171), (172, 172), (173, 173), (174, 174), (175, 175), (176, 176), (177, 177), (178, 178), (179, 179), (180, 180), (181, 181), (182, 182), (183, 183), (184, 184), (185, 185), (186, 186), (187, 187), (188, 188), (189, 189), (190, 190), (191, 191), (192, 192), (193, 193), (194, 194), (195, 195), (196, 196), (197, 197), (198, 198), (199, 199), (200, 200), (201, 201), (202, 202), (203, 203), (204, 204), (205, 205), (206, 206), (207, 207), (208, 208), (209, 209), (210, 210), (211, 211), (212, 212), (213, 213), (214, 214), (215, 215), (216, 216), (217, 217), (218, 218), (219, 219), (220, 220), (221, 221), (222, 222), (223, 223), (224, 224), (225, 225), (226, 226), (227, 227), (228, 228), (229, 229), (230, 230), (231, 231), (232, 232), (233, 233), (234, 234), (235, 235), (236, 236), (237, 237), (238, 238), (239, 239), (240, 240), (241, 241), (242, 242), (243, 243), (244, 244), (245, 245), (246, 246), (247, 247), (248, 248), (249, 249), (250, 250), (251, 251), (252, 252), (253, 253), (254, 254), (255, 255), (256, 256), (257, 257), (258, 258), (259, 259), (260, 260), (261, 261), (262, 262), (263, 263), (264, 264), (265, 265), (266, 266), (267, 267), (268, 268), (269, 269), (270, 270), (271, 271), (272, 272), (273, 273), (274, 274), (275, 275), (276, 276), (277, 277), (278, 278), (279, 279), (280, 280), (281, 281), (282, 282), (283, 283), (284, 284), (285, 285), (286, 286), (287, 287), (288, 288), (289, 289), (290, 290), (291, 291), (292, 292), (293, 293), (294, 294), (295, 295), (296, 296), (297, 297), (298, 298), (299, 299), (300, 300), (301, 301), (302, 302), (303, 303), (304, 304), (305, 305), (306, 306), (307, 307), (308, 308), (309, 309), (310, 310), (311, 311), (312, 312), (313, 313), (314, 314), (315, 315), (316, 316), (317, 317), (318, 318), (319, 319), (320, 320), (321, 321), (322, 322), (323, 323), (324, 324), (325, 325), (326, 326), (327, 327), (328, 328), (329, 329), (330, 330), (331, 331), (332, 332), (333, 333), (334, 334), (335, 335), (336, 336), (337, 337), (338, 338), (339, 339), (340, 340), (341, 341), (342, 342), (343, 343), (344, 344), (345, 345), (346, 346), (347, 347), (348, 348), (349, 349), (350, 350), (351, 351), (352, 352), (353, 353), (354, 354), (355, 355), (356, 356), (357, 357), (358, 358), (359, 359), (360, 360), (361, 361), (362, 362), (363, 363), (364, 364), (365, 365), (366, 366), (367, 367), (368, 368), (369, 369), (370, 370), (371, 371), (372, 372), (373, 373), (374, 374), (375, 375), (376, 376), (377, 377), (378, 378), (379, 379), (380, 380), (381, 381), (382, 382), (383, 383), (384, 384), (385, 385), (386, 386), (387, 387), (388, 388), (389, 389), (390, 390), (391, 391), (392, 392), (393, 393), (394, 394), (395, 395), (396, 396), (397, 397), (398, 398), (399, 399), (400, 400)], verbose_name='Variklio galia:')),
                ('engine_capacity', models.DecimalField(choices=[(Decimal('0.9'), Decimal('0.9')), (Decimal('1.0'), Decimal('1.0')), (Decimal('1.1'), Decimal('1.1')), (Decimal('1.2'), Decimal('1.2')), (Decimal('1.3'), Decimal('1.3')), (Decimal('1.4'), Decimal('1.4')), (Decimal('1.5'), Decimal('1.5')), (Decimal('1.6'), Decimal('1.6')), (Decimal('1.7'), Decimal('1.7')), (Decimal('1.8'), Decimal('1.8')), (Decimal('1.9'), Decimal('1.9')), (Decimal('2.0'), Decimal('2.0')), (Decimal('2.1'), Decimal('2.1')), (Decimal('2.2'), Decimal('2.2')), (Decimal('2.3'), Decimal('2.3')), (Decimal('2.4'), Decimal('2.4')), (Decimal('2.5'), Decimal('2.5')), (Decimal('2.6'), Decimal('2.6')), (Decimal('2.7'), Decimal('2.7')), (Decimal('2.8'), Decimal('2.8')), (Decimal('2.9'), Decimal('2.9')), (Decimal('3.0'), Decimal('3.0')), (Decimal('3.1'), Decimal('3.1')), (Decimal('3.2'), Decimal('3.2')), (Decimal('3.3'), Decimal('3.3')), (Decimal('3.4'), Decimal('3.4')), (Decimal('3.5'), Decimal('3.5')), (Decimal('3.6'), Decimal('3.6')), (Decimal('3.7'), Decimal('3.7')), (Decimal('3.8'), Decimal('3.8')), (Decimal('3.9'), Decimal('3.9')), (Decimal('4.0'), Decimal('4.0')), (Decimal('4.1'), Decimal('4.1')), (Decimal('4.2'), Decimal('4.2')), (Decimal('4.3'), Decimal('4.3')), (Decimal('4.4'), Decimal('4.4')), (Decimal('4.5'), Decimal('4.5')), (Decimal('4.6'), Decimal('4.6')), (Decimal('4.7'), Decimal('4.7')), (Decimal('4.8'), Decimal('4.8')), (Decimal('4.9'), Decimal('4.9')), (Decimal('5.0'), Decimal('5.0')), (Decimal('5.1'), Decimal('5.1')), (Decimal('5.2'), Decimal('5.2')), (Decimal('5.3'), Decimal('5.3')), (Decimal('5.4'), Decimal('5.4')), (Decimal('5.5'), Decimal('5.5')), (Decimal('5.6'), Decimal('5.6')), (Decimal('5.7'), Decimal('5.7')), (Decimal('5.8'), Decimal('5.8')), (Decimal('5.9'), Decimal('5.9')), (Decimal('6.0'), Decimal('6.0'))], decimal_places=1, max_digits=3, verbose_name='Variklio darbinis tūris:')),
                ('issue_notes', models.TextField(blank=True, null=True, verbose_name='Vizito priežastis:')),
                ('ordered_parts_description', models.TextField(blank=True, null=True, verbose_name='Užsakytos dalys:')),
                ('ordered_parts_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Užsakytų dalių kaina:')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Įkainis už remontą:')),
                ('repair_notes', models.TextField(blank=True, null=True, verbose_name='Mechaniko išvados:')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servizas.mechanic', verbose_name='Darbus atliko:')),
            ],
        ),
    ]
