# Generated by Django 5.0.2 on 2024-03-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='body_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='driven_axle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='engine_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='gearbox_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servizas.mechanic'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='ordered_parts_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
