# Generated by Django 5.0.2 on 2024-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='ph_number',
            field=models.CharField(max_length=15, verbose_name='Tel. nr.:'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='skills',
            field=models.CharField(max_length=100, verbose_name='Įgūdžiai:'),
        ),
    ]
